var annotated_dup =
[
    [ "Engine", "namespace_engine.html", [
      [ "AudioClip", "struct_engine_1_1_audio_clip.html", "struct_engine_1_1_audio_clip" ],
      [ "AudioManager", "class_engine_1_1_audio_manager.html", "class_engine_1_1_audio_manager" ],
      [ "Body", "class_engine_1_1_body.html", "class_engine_1_1_body" ],
      [ "Box2DDebugDraw", "class_engine_1_1_box2_d_debug_draw.html", "class_engine_1_1_box2_d_debug_draw" ],
      [ "Cache", "class_engine_1_1_cache.html", "class_engine_1_1_cache" ],
      [ "CacheElement", "class_engine_1_1_cache_element.html", "class_engine_1_1_cache_element" ],
      [ "ConfigManager", "class_engine_1_1_config_manager.html", "class_engine_1_1_config_manager" ],
      [ "ConfigObject", "class_engine_1_1_config_object.html", "class_engine_1_1_config_object" ],
      [ "ContactEvent", "struct_engine_1_1_contact_event.html", "struct_engine_1_1_contact_event" ],
      [ "ContactListener", "class_engine_1_1_contact_listener.html", "class_engine_1_1_contact_listener" ],
      [ "DebugDraw", "class_engine_1_1_debug_draw.html", null ],
      [ "EngineApp", "class_engine_1_1_engine_app.html", "class_engine_1_1_engine_app" ],
      [ "EngineMain", "class_engine_1_1_engine_main.html", null ],
      [ "Entity", "class_engine_1_1_entity.html", "class_engine_1_1_entity" ],
      [ "FontFile", "struct_engine_1_1_font_file.html", "struct_engine_1_1_font_file" ],
      [ "FontManager", "class_engine_1_1_font_manager.html", "class_engine_1_1_font_manager" ],
      [ "GameObject", "class_engine_1_1_game_object.html", "class_engine_1_1_game_object" ],
      [ "InputManager", "class_engine_1_1_input_manager.html", "class_engine_1_1_input_manager" ],
      [ "KeyEventArgs", "class_engine_1_1_key_event_args.html", "class_engine_1_1_key_event_args" ],
      [ "Logger", "class_engine_1_1_logger.html", null ],
      [ "MouseEventArgs", "class_engine_1_1_mouse_event_args.html", "class_engine_1_1_mouse_event_args" ],
      [ "MouseMoveEventArgs", "class_engine_1_1_mouse_move_event_args.html", "class_engine_1_1_mouse_move_event_args" ],
      [ "PhysicsEntity", "class_engine_1_1_physics_entity.html", "class_engine_1_1_physics_entity" ],
      [ "PhysicsManager", "class_engine_1_1_physics_manager.html", "class_engine_1_1_physics_manager" ],
      [ "RendererManager", "class_engine_1_1_renderer_manager.html", "class_engine_1_1_renderer_manager" ],
      [ "ResourceManager", "class_engine_1_1_resource_manager.html", null ],
      [ "Sprite", "class_engine_1_1_sprite.html", "class_engine_1_1_sprite" ],
      [ "SpriteCacheElement", "class_engine_1_1_sprite_cache_element.html", "class_engine_1_1_sprite_cache_element" ],
      [ "TextElement", "class_engine_1_1_text_element.html", "class_engine_1_1_text_element" ],
      [ "UIButton", "class_engine_1_1_u_i_button.html", "class_engine_1_1_u_i_button" ],
      [ "UIElement", "class_engine_1_1_u_i_element.html", "class_engine_1_1_u_i_element" ],
      [ "UIManager", "class_engine_1_1_u_i_manager.html", "class_engine_1_1_u_i_manager" ],
      [ "Utils", "class_engine_1_1_utils.html", null ],
      [ "WindowManager", "class_engine_1_1_window_manager.html", "class_engine_1_1_window_manager" ]
    ] ]
];