var dir_8351ebc186bef09292184abd1c604a4a =
[
    [ "SDL2.cs", "_s_d_l2_8cs.html", [
      [ "SDL2.SDL.SDL_RWops", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___r_wops.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___r_wops" ],
      [ "SDL2.SDL.SDL_MessageBoxButtonData", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_button_data.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_button_data" ],
      [ "SDL2.SDL.SDL_MessageBoxColor", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_color.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_color" ],
      [ "SDL2.SDL.SDL_MessageBoxColorScheme", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_color_scheme.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_color_scheme" ],
      [ "SDL2.SDL.SDL_MessageBoxData", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_data.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_data" ],
      [ "SDL2.SDL.SDL_version", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l__version.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l__version" ],
      [ "SDL2.SDL.SDL_DisplayMode", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___display_mode.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___display_mode" ],
      [ "SDL2.SDL.SDL_RendererInfo", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___renderer_info.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___renderer_info" ],
      [ "SDL2.SDL.SDL_Color", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___color.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___color" ],
      [ "SDL2.SDL.SDL_Palette", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___palette.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___palette" ],
      [ "SDL2.SDL.SDL_PixelFormat", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___pixel_format.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___pixel_format" ],
      [ "SDL2.SDL.SDL_Point", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___point.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___point" ],
      [ "SDL2.SDL.SDL_Rect", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___rect.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___rect" ],
      [ "SDL2.SDL.SDL_FPoint", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___f_point.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___f_point" ],
      [ "SDL2.SDL.SDL_FRect", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___f_rect.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___f_rect" ],
      [ "SDL2.SDL.SDL_Surface", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___surface.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___surface" ],
      [ "SDL2.SDL.SDL_GenericEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___generic_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___generic_event" ],
      [ "SDL2.SDL.SDL_DisplayEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___display_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___display_event" ],
      [ "SDL2.SDL.SDL_WindowEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___window_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___window_event" ],
      [ "SDL2.SDL.SDL_KeyboardEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___keyboard_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___keyboard_event" ],
      [ "SDL2.SDL.SDL_TextEditingEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___text_editing_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___text_editing_event" ],
      [ "SDL2.SDL.SDL_TextInputEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___text_input_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___text_input_event" ],
      [ "SDL2.SDL.SDL_MouseMotionEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___mouse_motion_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___mouse_motion_event" ],
      [ "SDL2.SDL.SDL_MouseButtonEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___mouse_button_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___mouse_button_event" ],
      [ "SDL2.SDL.SDL_MouseWheelEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___mouse_wheel_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___mouse_wheel_event" ],
      [ "SDL2.SDL.SDL_JoyAxisEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_axis_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_axis_event" ],
      [ "SDL2.SDL.SDL_JoyBallEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_ball_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_ball_event" ],
      [ "SDL2.SDL.SDL_JoyHatEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_hat_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_hat_event" ],
      [ "SDL2.SDL.SDL_JoyButtonEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_button_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_button_event" ],
      [ "SDL2.SDL.SDL_JoyDeviceEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_device_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_device_event" ],
      [ "SDL2.SDL.SDL_ControllerAxisEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_axis_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_axis_event" ],
      [ "SDL2.SDL.SDL_ControllerButtonEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_button_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_button_event" ],
      [ "SDL2.SDL.SDL_ControllerDeviceEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_device_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_device_event" ],
      [ "SDL2.SDL.SDL_ControllerTouchpadEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_touchpad_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_touchpad_event" ],
      [ "SDL2.SDL.SDL_ControllerSensorEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_sensor_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_sensor_event" ],
      [ "SDL2.SDL.SDL_AudioDeviceEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___audio_device_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___audio_device_event" ],
      [ "SDL2.SDL.SDL_TouchFingerEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___touch_finger_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___touch_finger_event" ],
      [ "SDL2.SDL.SDL_MultiGestureEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___multi_gesture_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___multi_gesture_event" ],
      [ "SDL2.SDL.SDL_DollarGestureEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___dollar_gesture_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___dollar_gesture_event" ],
      [ "SDL2.SDL.SDL_DropEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___drop_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___drop_event" ],
      [ "SDL2.SDL.SDL_SensorEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___sensor_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___sensor_event" ],
      [ "SDL2.SDL.SDL_QuitEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___quit_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___quit_event" ],
      [ "SDL2.SDL.SDL_UserEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___user_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___user_event" ],
      [ "SDL2.SDL.SDL_SysWMEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___sys_w_m_event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___sys_w_m_event" ],
      [ "SDL2.SDL.SDL_Event", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___event.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___event" ],
      [ "SDL2.SDL.SDL_Keysym", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___keysym.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___keysym" ],
      [ "SDL2.SDL.SDL_Finger", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___finger.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___finger" ],
      [ "SDL2.SDL.INTERNAL_GameControllerButtonBind_hat", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l___game_controller_button_bind__hat.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l___game_controller_button_bind__hat" ],
      [ "SDL2.SDL.INTERNAL_GameControllerButtonBind_union", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l___game_controller_button_bind__union.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l___game_controller_button_bind__union" ],
      [ "SDL2.SDL.SDL_GameControllerButtonBind", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___game_controller_button_bind.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___game_controller_button_bind" ],
      [ "SDL2.SDL.SDL_HapticDirection", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_direction.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_direction" ],
      [ "SDL2.SDL.SDL_HapticConstant", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_constant.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_constant" ],
      [ "SDL2.SDL.SDL_HapticPeriodic", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_periodic.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_periodic" ],
      [ "SDL2.SDL.SDL_HapticCondition", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_condition.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_condition" ],
      [ "SDL2.SDL.SDL_HapticRamp", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_ramp.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_ramp" ],
      [ "SDL2.SDL.SDL_HapticLeftRight", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_left_right.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_left_right" ],
      [ "SDL2.SDL.SDL_HapticCustom", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_custom.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_custom" ],
      [ "SDL2.SDL.SDL_HapticEffect", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_effect.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_effect" ],
      [ "SDL2.SDL.SDL_AudioSpec", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___audio_spec.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___audio_spec" ],
      [ "SDL2.SDL.INTERNAL_windows_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__windows__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__windows__wminfo" ],
      [ "SDL2.SDL.INTERNAL_winrt_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__winrt__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__winrt__wminfo" ],
      [ "SDL2.SDL.INTERNAL_x11_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__x11__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__x11__wminfo" ],
      [ "SDL2.SDL.INTERNAL_directfb_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__directfb__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__directfb__wminfo" ],
      [ "SDL2.SDL.INTERNAL_cocoa_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__cocoa__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__cocoa__wminfo" ],
      [ "SDL2.SDL.INTERNAL_uikit_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__uikit__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__uikit__wminfo" ],
      [ "SDL2.SDL.INTERNAL_wayland_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__wayland__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__wayland__wminfo" ],
      [ "SDL2.SDL.INTERNAL_mir_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__mir__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__mir__wminfo" ],
      [ "SDL2.SDL.INTERNAL_android_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__android__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__android__wminfo" ],
      [ "SDL2.SDL.INTERNAL_vivante_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__vivante__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__vivante__wminfo" ],
      [ "SDL2.SDL.INTERNAL_os2_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__os2__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__os2__wminfo" ],
      [ "SDL2.SDL.INTERNAL_kmsdrm_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__kmsdrm__wminfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__kmsdrm__wminfo" ],
      [ "SDL2.SDL.INTERNAL_SysWMDriverUnion", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l___sys_w_m_driver_union.html", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l___sys_w_m_driver_union" ],
      [ "SDL2.SDL.SDL_SysWMinfo", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___sys_w_minfo.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___sys_w_minfo" ],
      [ "SDL2.SDL.SDL_Locale", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___locale.html", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___locale" ]
    ] ],
    [ "SDL2_image.cs", "_s_d_l2__image_8cs.html", [
      [ "SDL2.SDL_image.IMG_Animation", "struct_s_d_l2_1_1_s_d_l__image_1_1_i_m_g___animation.html", "struct_s_d_l2_1_1_s_d_l__image_1_1_i_m_g___animation" ]
    ] ],
    [ "SDL2_mixer.cs", "_s_d_l2__mixer_8cs.html", [
      [ "SDL2.SDL_mixer.MIX_Chunk", "struct_s_d_l2_1_1_s_d_l__mixer_1_1_m_i_x___chunk.html", "struct_s_d_l2_1_1_s_d_l__mixer_1_1_m_i_x___chunk" ]
    ] ],
    [ "SDL2_ttf.cs", "_s_d_l2__ttf_8cs.html", null ]
];