var hierarchy =
[
    [ "Engine.InputAction.ActionMapping", "struct_engine_1_1_input_action_1_1_action_mapping.html", null ],
    [ "Engine.AnimationMetaFile.AnimationInfo", "struct_engine_1_1_animation_meta_file_1_1_animation_info.html", null ],
    [ "Attribute", null, [
      [ "Engine.TiledObjectMapping", "class_engine_1_1_tiled_object_mapping.html", null ]
    ] ],
    [ "Engine.AudioClip", "struct_engine_1_1_audio_clip.html", null ],
    [ "Engine.AudioManager", "class_engine_1_1_audio_manager.html", null ],
    [ "Engine.GamepadMapping.AxisMapping", "struct_engine_1_1_gamepad_mapping_1_1_axis_mapping.html", null ],
    [ "Engine.BatchedRendererElementInfo", "struct_engine_1_1_batched_renderer_element_info.html", null ],
    [ "Engine.Body", "class_engine_1_1_body.html", null ],
    [ "Engine.Cache< ElementType >", "class_engine_1_1_cache.html", null ],
    [ "Engine.CacheElement", "class_engine_1_1_cache_element.html", [
      [ "Engine.SpriteCacheElement", "class_engine_1_1_sprite_cache_element.html", null ]
    ] ],
    [ "Engine.Camera", "class_engine_1_1_camera.html", null ],
    [ "Engine.ConfigManager", "class_engine_1_1_config_manager.html", null ],
    [ "Engine.ConfigObject", "class_engine_1_1_config_object.html", [
      [ "Engine.AnimationMetaFile", "class_engine_1_1_animation_meta_file.html", null ],
      [ "Engine.GamepadsConfig", "class_engine_1_1_gamepads_config.html", null ],
      [ "Engine.InputMappingConfig", "class_engine_1_1_input_mapping_config.html", null ]
    ] ],
    [ "Engine.ContactEvent", "class_engine_1_1_contact_event.html", null ],
    [ "Dynamics.ContactListener", null, [
      [ "Engine.ContactListener", "class_engine_1_1_contact_listener.html", null ]
    ] ],
    [ "Dynamics.DebugDraw", null, [
      [ "Engine.Box2DDebugDraw", "class_engine_1_1_box2_d_debug_draw.html", null ]
    ] ],
    [ "Engine.DebugDraw", "class_engine_1_1_debug_draw.html", null ],
    [ "Engine.DiscordManager", "class_engine_1_1_discord_manager.html", null ],
    [ "Engine.EngineApp", "class_engine_1_1_engine_app.html", null ],
    [ "Engine.EngineMain", "class_engine_1_1_engine_main.html", null ],
    [ "EventArgs", null, [
      [ "Engine.ActionEventArgs", "class_engine_1_1_action_event_args.html", null ],
      [ "Engine.KeyEventArgs", "class_engine_1_1_key_event_args.html", null ],
      [ "Engine.MouseEventArgs", "class_engine_1_1_mouse_event_args.html", null ],
      [ "Engine.MouseMoveEventArgs", "class_engine_1_1_mouse_move_event_args.html", null ],
      [ "Engine.MouseWheelEventArgs", "class_engine_1_1_mouse_wheel_event_args.html", null ],
      [ "Engine.ResolutionChangedEventArgs", "class_engine_1_1_resolution_changed_event_args.html", null ]
    ] ],
    [ "Exception", null, [
      [ "TiledCS.TiledException", "class_tiled_c_s_1_1_tiled_exception.html", null ]
    ] ],
    [ "FastNoiseLite", "class_fast_noise_lite.html", null ],
    [ "Engine.FontFile", "struct_engine_1_1_font_file.html", null ],
    [ "Engine.FontManager", "class_engine_1_1_font_manager.html", null ],
    [ "Engine.GameObject", "class_engine_1_1_game_object.html", [
      [ "Engine.Entity", "class_engine_1_1_entity.html", [
        [ "Engine.AnimatedSprite", "class_engine_1_1_animated_sprite.html", null ],
        [ "Engine.PhysicsEntity", "class_engine_1_1_physics_entity.html", null ],
        [ "Engine.Sprite", "class_engine_1_1_sprite.html", null ],
        [ "Engine.TextElement", "class_engine_1_1_text_element.html", null ]
      ] ]
    ] ],
    [ "Engine.GamepadMapping", "class_engine_1_1_gamepad_mapping.html", null ],
    [ "Engine.GameStateManager", "class_engine_1_1_game_state_manager.html", null ],
    [ "Engine.IGameState", "interface_engine_1_1_i_game_state.html", null ],
    [ "SDL2.SDL_image.IMG_Animation", "struct_s_d_l2_1_1_s_d_l__image_1_1_i_m_g___animation.html", null ],
    [ "Engine.InputAction", "class_engine_1_1_input_action.html", null ],
    [ "Engine.InputManager", "class_engine_1_1_input_manager.html", null ],
    [ "Engine.InputAction.ActionMapping.InputModifiers", "struct_engine_1_1_input_action_1_1_action_mapping_1_1_input_modifiers.html", null ],
    [ "SDL2.SDL.INTERNAL_android_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__android__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_cocoa_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__cocoa__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_directfb_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__directfb__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_GameControllerButtonBind_hat", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l___game_controller_button_bind__hat.html", null ],
    [ "SDL2.SDL.INTERNAL_GameControllerButtonBind_union", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l___game_controller_button_bind__union.html", null ],
    [ "SDL2.SDL.INTERNAL_kmsdrm_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__kmsdrm__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_mir_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__mir__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_os2_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__os2__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_SysWMDriverUnion", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l___sys_w_m_driver_union.html", null ],
    [ "SDL2.SDL.INTERNAL_uikit_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__uikit__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_vivante_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__vivante__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_wayland_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__wayland__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_windows_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__windows__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_winrt_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__winrt__wminfo.html", null ],
    [ "SDL2.SDL.INTERNAL_x11_wminfo", "struct_s_d_l2_1_1_s_d_l_1_1_i_n_t_e_r_n_a_l__x11__wminfo.html", null ],
    [ "Engine.ITiledObjectMappingInterface", "interface_engine_1_1_i_tiled_object_mapping_interface.html", null ],
    [ "Engine.Logger", "class_engine_1_1_logger.html", null ],
    [ "Engine.MathUtils", "class_engine_1_1_math_utils.html", null ],
    [ "SDL2.SDL_mixer.MIX_Chunk", "struct_s_d_l2_1_1_s_d_l__mixer_1_1_m_i_x___chunk.html", null ],
    [ "Engine.OpenGLUtilities", "class_engine_1_1_open_g_l_utilities.html", null ],
    [ "Engine.PhysicsManager", "class_engine_1_1_physics_manager.html", null ],
    [ "Engine.RendererManager", "class_engine_1_1_renderer_manager.html", null ],
    [ "Engine.ResourceManager", "class_engine_1_1_resource_manager.html", null ],
    [ "SDL2.SDL.SDL_AudioDeviceEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___audio_device_event.html", null ],
    [ "SDL2.SDL.SDL_AudioSpec", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___audio_spec.html", null ],
    [ "SDL2.SDL.SDL_Color", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___color.html", null ],
    [ "SDL2.SDL.SDL_ControllerAxisEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_axis_event.html", null ],
    [ "SDL2.SDL.SDL_ControllerButtonEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_button_event.html", null ],
    [ "SDL2.SDL.SDL_ControllerDeviceEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_device_event.html", null ],
    [ "SDL2.SDL.SDL_ControllerSensorEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_sensor_event.html", null ],
    [ "SDL2.SDL.SDL_ControllerTouchpadEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___controller_touchpad_event.html", null ],
    [ "SDL2.SDL.SDL_DisplayEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___display_event.html", null ],
    [ "SDL2.SDL.SDL_DisplayMode", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___display_mode.html", null ],
    [ "SDL2.SDL.SDL_DollarGestureEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___dollar_gesture_event.html", null ],
    [ "SDL2.SDL.SDL_DropEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___drop_event.html", null ],
    [ "SDL2.SDL.SDL_Event", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___event.html", null ],
    [ "SDL2.SDL.SDL_Finger", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___finger.html", null ],
    [ "SDL2.SDL.SDL_FPoint", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___f_point.html", null ],
    [ "SDL2.SDL.SDL_FRect", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___f_rect.html", null ],
    [ "SDL2.SDL.SDL_GameControllerButtonBind", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___game_controller_button_bind.html", null ],
    [ "SDL2.SDL.SDL_GenericEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___generic_event.html", null ],
    [ "SDL2.SDL.SDL_HapticCondition", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_condition.html", null ],
    [ "SDL2.SDL.SDL_HapticConstant", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_constant.html", null ],
    [ "SDL2.SDL.SDL_HapticCustom", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_custom.html", null ],
    [ "SDL2.SDL.SDL_HapticDirection", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_direction.html", null ],
    [ "SDL2.SDL.SDL_HapticEffect", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_effect.html", null ],
    [ "SDL2.SDL.SDL_HapticLeftRight", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_left_right.html", null ],
    [ "SDL2.SDL.SDL_HapticPeriodic", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_periodic.html", null ],
    [ "SDL2.SDL.SDL_HapticRamp", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___haptic_ramp.html", null ],
    [ "SDL2.SDL.SDL_JoyAxisEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_axis_event.html", null ],
    [ "SDL2.SDL.SDL_JoyBallEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_ball_event.html", null ],
    [ "SDL2.SDL.SDL_JoyButtonEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_button_event.html", null ],
    [ "SDL2.SDL.SDL_JoyDeviceEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_device_event.html", null ],
    [ "SDL2.SDL.SDL_JoyHatEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___joy_hat_event.html", null ],
    [ "SDL2.SDL.SDL_KeyboardEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___keyboard_event.html", null ],
    [ "SDL2.SDL.SDL_Keysym", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___keysym.html", null ],
    [ "SDL2.SDL.SDL_Locale", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___locale.html", null ],
    [ "SDL2.SDL.SDL_MessageBoxButtonData", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_button_data.html", null ],
    [ "SDL2.SDL.SDL_MessageBoxColor", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_color.html", null ],
    [ "SDL2.SDL.SDL_MessageBoxColorScheme", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_color_scheme.html", null ],
    [ "SDL2.SDL.SDL_MessageBoxData", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___message_box_data.html", null ],
    [ "SDL2.SDL.SDL_MouseButtonEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___mouse_button_event.html", null ],
    [ "SDL2.SDL.SDL_MouseMotionEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___mouse_motion_event.html", null ],
    [ "SDL2.SDL.SDL_MouseWheelEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___mouse_wheel_event.html", null ],
    [ "SDL2.SDL.SDL_MultiGestureEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___multi_gesture_event.html", null ],
    [ "SDL2.SDL.SDL_Palette", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___palette.html", null ],
    [ "SDL2.SDL.SDL_PixelFormat", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___pixel_format.html", null ],
    [ "SDL2.SDL.SDL_Point", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___point.html", null ],
    [ "SDL2.SDL.SDL_QuitEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___quit_event.html", null ],
    [ "SDL2.SDL.SDL_Rect", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___rect.html", null ],
    [ "SDL2.SDL.SDL_RendererInfo", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___renderer_info.html", null ],
    [ "SDL2.SDL.SDL_RWops", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___r_wops.html", null ],
    [ "SDL2.SDL.SDL_SensorEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___sensor_event.html", null ],
    [ "SDL2.SDL.SDL_Surface", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___surface.html", null ],
    [ "SDL2.SDL.SDL_SysWMEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___sys_w_m_event.html", null ],
    [ "SDL2.SDL.SDL_SysWMinfo", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___sys_w_minfo.html", null ],
    [ "SDL2.SDL.SDL_TextEditingEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___text_editing_event.html", null ],
    [ "SDL2.SDL.SDL_TextInputEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___text_input_event.html", null ],
    [ "SDL2.SDL.SDL_TouchFingerEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___touch_finger_event.html", null ],
    [ "SDL2.SDL.SDL_UserEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___user_event.html", null ],
    [ "SDL2.SDL.SDL_version", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l__version.html", null ],
    [ "SDL2.SDL.SDL_WindowEvent", "struct_s_d_l2_1_1_s_d_l_1_1_s_d_l___window_event.html", null ],
    [ "Engine.AnimationMetaFile.SpritesheetInfo", "struct_engine_1_1_animation_meta_file_1_1_spritesheet_info.html", null ],
    [ "TiledCS.TiledEllipse", "class_tiled_c_s_1_1_tiled_ellipse.html", null ],
    [ "TiledCS.TiledGroup", "class_tiled_c_s_1_1_tiled_group.html", null ],
    [ "TiledCS.TiledImage", "class_tiled_c_s_1_1_tiled_image.html", null ],
    [ "TiledCS.TiledLayer", "class_tiled_c_s_1_1_tiled_layer.html", null ],
    [ "TiledCS.TiledMap", "class_tiled_c_s_1_1_tiled_map.html", null ],
    [ "TiledCS.TiledMapTileset", "class_tiled_c_s_1_1_tiled_map_tileset.html", null ],
    [ "Engine.TiledMapUtils", "class_engine_1_1_tiled_map_utils.html", null ],
    [ "TiledCS.TiledObject", "class_tiled_c_s_1_1_tiled_object.html", null ],
    [ "TiledCS.TiledPoint", "class_tiled_c_s_1_1_tiled_point.html", null ],
    [ "TiledCS.TiledPolygon", "class_tiled_c_s_1_1_tiled_polygon.html", null ],
    [ "TiledCS.TiledPolyline", "class_tiled_c_s_1_1_tiled_polyline.html", null ],
    [ "TiledCS.TiledProperty", "class_tiled_c_s_1_1_tiled_property.html", null ],
    [ "TiledCS.TiledSourceRect", "class_tiled_c_s_1_1_tiled_source_rect.html", null ],
    [ "TiledCS.TiledTerrain", "class_tiled_c_s_1_1_tiled_terrain.html", null ],
    [ "TiledCS.TiledTile", "class_tiled_c_s_1_1_tiled_tile.html", null ],
    [ "TiledCS.TiledTileAnimation", "class_tiled_c_s_1_1_tiled_tile_animation.html", null ],
    [ "TiledCS.TiledTileset", "class_tiled_c_s_1_1_tiled_tileset.html", null ],
    [ "Engine.Timer", "class_engine_1_1_timer.html", null ],
    [ "Engine.UIElement", "class_engine_1_1_u_i_element.html", [
      [ "Engine.UIAnimatedSprite", "class_engine_1_1_u_i_animated_sprite.html", null ],
      [ "Engine.UIButton", "class_engine_1_1_u_i_button.html", null ],
      [ "Engine.UISprite", "class_engine_1_1_u_i_sprite.html", null ],
      [ "Engine.UIText", "class_engine_1_1_u_i_text.html", null ]
    ] ],
    [ "Engine.UIManager", "class_engine_1_1_u_i_manager.html", null ],
    [ "Engine.Utils", "class_engine_1_1_utils.html", null ],
    [ "Engine.WindowManager", "class_engine_1_1_window_manager.html", null ]
];